// RepositoryDemoApplication.java
// Seeds a bit of data and shows the repository working end to end - findAll()
// is a method we never implemented ourselves; Spring generated it.

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class RepositoryDemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(RepositoryDemoApplication.class, args);
    }

    @Bean
    CommandLineRunner demo(AuthorRepository authorRepository, BookRepository bookRepository) {
        return args -> {
            Author author = new Author("Robert C. Martin");
            author.addBook(new Book("Clean Code", 899.0));
            author.addBook(new Book("Effective Java", 799.0));

            authorRepository.save(author); // cascades and saves both books too

            System.out.println("Repository interface generated by Spring, no implementation written by hand.");
            System.out.println("Books in catalog: " + bookRepository.findAll());
        };
    }
}
